### ISSUE TITLE
SCSS Compile not working

### ISSUE THREAD

**Issue by pablonnaoji** [lashkari/gadget-devtools#4]
Hi Shahab, 

Thanks for the awesome gadget. I have one issue that were trying to iron out. While the js, and css files are minified alright, were having trouble compiling sass/less. 

The file is like: "code-master.css"
the contents looks like this: 
# weather {

```
position: relative;
display: block;
width: 300px;
font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
letter-spacing: 0.03em;
}
```

.weather-teaser {
    position: relative;
    display: block;
    width: 70px;
    height: 30px;
    color: #d7d2cc;
    text-align: center;
    line-height: 1.8em;
    background-color: #968b84;
    border-bottom: 1px solid #d7d2cc;
    }

// 
When I click on the plug button to the far right, and click "developer tools" the button says "publish code-master.css, but when I hit the button nothing happens. No files are created. 
Do you know what could be wrong? 

Thanks in advance Shahab!

**Comment by lashkari** [comment]
Just to clarify, is the file you are viewing in the CMS named `code-master.css` or `code-master.scss`?

**Comment by pablonnaoji** [comment]
![screen shot 2016-05-31 at 1 51 33 pm](https://cloud.githubusercontent.com/assets/15187159/15690137/f76a50ee-2736-11e6-84cd-ff1fb33e1392.png)
The files are "scss" but in the minification tool its listed as "css". I think thats the problem.

**Comment by lashkari** [comment]
I believe the problem here is that you are using `@import`, which the gadget doesn't support.

Basically, the gadget is sending the contents of only the current file to the back-end (of the gadget, not OU Campus). So when it encounters the imports, it's probably erroring out.

I don't think there's a simple solution I can implement to handle this case. I'll look into it some more, but for now I think I'm just going to have to add a disclaimer that this is a limitation of the gadget.
